FROM node:18-alpine

# ===================== Set arguments ===================== #
# CMS
ARG CMS_URL
ARG NEXT_PUBLIC_CMS_URL
ARG MONGODB_URL
ARG CMS_SECRET
ARG STORAGE_FILES

# WEB
ARG LAND_URL
ARG PAYLOAD_PUBLIC_LAND_URL
ARG PAYLOAD_PUBLIC_ASPIRE_URL
ARG ASPIRE_ZOHO_BOT_WIDGET_CODE
ARG NEXT_PUBLIC_ASPIRE_ZOHO_BOT_WIDGET_CODE
ARG PAYLOAD_PUBLIC_PRESTIGE_URL
ARG PRESTIGE_ZOHO_BOT_WIDGET_CODE
ARG NEXT_PUBLIC_PRESTIGE_ZOHO_BOT_WIDGET_CODE
ARG PAYLOAD_PUBLIC_FUTURA_URL
ARG FUTURA_ZOHO_BOT_WIDGET_CODE
ARG NEXT_PUBLIC_FUTURA_ZOHO_BOT_WIDGET_CODE

# 3RD PARTY
ARG SENDGRID_API_KEY
ARG GMAPS_TOKEN
ARG MANATAL_TOKEN
ARG ZOHO_REFRESH_TOKEN
ARG NEXT_PUBLIC_ZOHO_REFRESH_TOKEN
ARG ZOHO_CLIENT_ID
ARG NEXT_PUBLIC_ZOHO_CLIENT_ID
ARG ZOHO_CLIENT_SECRET
ARG NEXT_PUBLIC_ZOHO_CLIENT_SECRET
ARG ZOHO_REFRESH_TOKEN_URL
ARG ZOHO_LEADS_URL
ARG MANATAL_CLIENT_ID
ARG MANATAL_ORG
ARG NEXT_PUBLIC_ZOHO_BOT_WIDGET_CODE
ARG PSE_URL

# CLOUD
ARG PAYLOAD_PUBLIC_S3_BUCKET
ARG S3_BUCKET
ARG ZOHO_BOT_WIDGET_CODE
ARG ACCESS_KEY_ID
ARG SECRET_ACCESS_KEY
ARG REGION

# ===================== Set environment variables ===================== #
ENV CMS_URL=$CMS_URL
ENV NEXT_PUBLIC_CMS_URL=$NEXT_PUBLIC_CMS_URL
ENV MONGODB_URL=$MONGODB_URL
ENV CMS_SECRET=$CMS_SECRET
ENV STORAGE_FILES=$STORAGE_FILES
ENV LAND_URL=$LAND_URL
ENV PAYLOAD_PUBLIC_LAND_URL=$PAYLOAD_PUBLIC_LAND_URL
ENV PAYLOAD_PUBLIC_ASPIRE_URL=$PAYLOAD_PUBLIC_ASPIRE_URL
ENV ASPIRE_ZOHO_BOT_WIDGET_CODE=$ASPIRE_ZOHO_BOT_WIDGET_CODE
ENV NEXT_PUBLIC_ASPIRE_ZOHO_BOT_WIDGET_CODE=$NEXT_PUBLIC_ASPIRE_ZOHO_BOT_WIDGET_CODE
ENV PAYLOAD_PUBLIC_PRESTIGE_URL=$PAYLOAD_PUBLIC_PRESTIGE_URL
ENV PRESTIGE_ZOHO_BOT_WIDGET_CODE=$PRESTIGE_ZOHO_BOT_WIDGET_CODE
ENV NEXT_PUBLIC_PRESTIGE_ZOHO_BOT_WIDGET_CODE=$NEXT_PUBLIC_PRESTIGE_ZOHO_BOT_WIDGET_CODE
ENV PAYLOAD_PUBLIC_FUTURA_URL=$PAYLOAD_PUBLIC_FUTURA_URL
ENV FUTURA_ZOHO_BOT_WIDGET_CODE=$FUTURA_ZOHO_BOT_WIDGET_CODE
ENV NEXT_PUBLIC_FUTURA_ZOHO_BOT_WIDGET_CODE=$NEXT_PUBLIC_FUTURA_ZOHO_BOT_WIDGET_CODE
ENV SENDGRID_API_KEY=$SENDGRID_API_KEY
ENV GMAPS_TOKEN=$GMAPS_TOKEN
ENV MANATAL_TOKEN=$MANATAL_TOKEN
ENV ZOHO_REFRESH_TOKEN=$ZOHO_REFRESH_TOKEN
ENV NEXT_PUBLIC_ZOHO_REFRESH_TOKEN=$NEXT_PUBLIC_ZOHO_REFRESH_TOKEN
ENV ZOHO_CLIENT_ID=$ZOHO_CLIENT_ID
ENV NEXT_PUBLIC_ZOHO_CLIENT_ID=$NEXT_PUBLIC_ZOHO_CLIENT_ID
ENV ZOHO_CLIENT_SECRET=$ZOHO_CLIENT_SECRET
ENV NEXT_PUBLIC_ZOHO_CLIENT_SECRET=$NEXT_PUBLIC_ZOHO_CLIENT_SECRET
ENV ZOHO_REFRESH_TOKEN_URL=$ZOHO_REFRESH_TOKEN_URL
ENV ZOHO_LEADS_URL=$ZOHO_LEADS_URL
ENV NEXT_PUBLIC_ZOHO_BOT_WIDGET_CODE=$NEXT_PUBLIC_ZOHO_BOT_WIDGET_CODE
ENV MANATAL_CLIENT_ID=$MANATAL_CLIENT_ID
ENV MANATAL_ORG=$MANATAL_ORG
ENV PAYLOAD_PUBLIC_S3_BUCKET=$PAYLOAD_PUBLIC_S3_BUCKET
ENV S3_BUCKET=$S3_BUCKET
ENV ZOHO_BOT_WIDGET_CODE=$ZOHO_BOT_WIDGET_CODE
ENV PSE_URL=$PSE_URL
ENV ACCESS_KEY_ID=$ACCESS_KEY_ID
ENV SECRET_ACCESS_KEY=$SECRET_ACCESS_KEY
ENV REGION=$REGION

# ===================== Install required dependencies ===================== #
RUN apk update \
 && apk add python3 make g++
# ===================== Copy application code ===================== #
WORKDIR /home/node
COPY . /home/node
