import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import "./globals.css";
import React from "react";
import type { Metadata } from "next";
import localFont from "next/font/local";
import Footer from "./containers/footer";
import Header from "./containers/header";
import StickyButtons from "./components/stickyButtons";
import { VirtualTourProvider } from "./context/VirtualTourContext";
import { VirtualTourUrlProvider } from "./context/VirtualTourUrlContext";
import ProjectProvider from "@/app/context/Project";

export const metadata: Metadata = {
  title: "Filinvest Futura",
  description: "Generated by create next app",
};

const nunito = localFont({
  src: [
    {
      path: "../public/assets/fonts/NunitoSans-VariableFont_YTLC,opsz,wdth,wght.ttf",
      weight: "400",
    },
  ],
  variable: "--font-nunito",
});

const marcellus = localFont({
  src: [
    {
      path: "../public/assets/fonts/Marcellus-Regular.ttf",
      weight: "400",
    },
  ],
  variable: "--font-marcellus",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`${nunito.variable} font-sans ${marcellus.variable}`}
    >
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Quicksand:wght@300;400;500;600;700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className="bg-[#FFF8F8] overflow-x-hidden mx-auto">
        <ProjectProvider>
          <VirtualTourProvider>
            <VirtualTourUrlProvider>
              <Header />
              {children}
              <StickyButtons />
              <Footer />
            </VirtualTourUrlProvider>
          </VirtualTourProvider>
        </ProjectProvider>
      </body>
    </html>
  );
}
