import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import "./globals.css";
import React from "react";
import cn from "classnames";
import type { Metadata } from "next";
import localFont from "next/font/local";
import Footer from "./containers/footer_new";
import HeaderNew from "./containers/header_new";
import { Floating } from "./components/general/floating";
import Consent from "./components/consent";

export const metadata: Metadata = {
  title: "Filinvest Prestige",
  description: "Generated by create next app",
};

// const nunito = localFont({
//   src: [
//     {
//       path: "../public/assets/fonts/NunitoSans-VariableFont_YTLC,opsz,wdth,wght.ttf",
//       // weight: "400",
//     },
//   ],
//   variable: "--font-nunito",
// });

const nunito = localFont({
  src: [
    {
      path: "../public/assets/fonts/Nunito-VariableFont_wght.ttf",
      // weight: "400",
    },
  ],
  variable: "--font-nunito",
});

const cormorant = localFont({
  src: [
    {
      path: "../public/assets/fonts/Cormorant-VariableFont_wght.ttf",
      // weight: "400",
    },
  ],
  variable: "--font-cormorant",
});

const brittany = localFont({
  src: [
    {
      path: "../public/assets/fonts/BrittanySignature.ttf",
      weight: "400",
    },
  ],
  variable: "--font-brittany",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={cn(
        "font-sans scroll-smooth",
        nunito.variable,
        brittany.variable,
        cormorant.variable
      )}
    >
      <body>
        <HeaderNew />
        {children}
        <Footer />
        <Floating />
        <Consent />
      </body>
    </html>
  );
}
